### ISSUE TITLE
Create new events (Database, FaceBook)

### ISSUE THREAD

**Issue by chrihand** [ung-it/UngIT#45]

**Comment by skaugvoll** [comment]
I'm not allowed to create a new event 

Test Sigve Tjohei
Navn på aktivitet

16.03.2017
Dato

13.20
Tid start

14.00
Tid slutt

Skaugvoll Gård
Sted
Tilpasninger
accessibleRullestolvisibilityBlinde
accessibilityEkstra assistentcancelhearingDøvecancel

Frivilig
Arrangør

Test av en test 12345
Om arrangement
Arrangement krever registrering

1000


was my parameters, tested 11:44am 14.3.17
