### ISSUE TITLE
Create an installation for Babak

### ISSUE THREAD

**Issue by chrihand** [ung-it/UngIT#53]
When new version is made, it should be easy to update

**Comment by skaugvoll** [comment]
Babak trenger en AWS konto, så kan jeg gi han en Image fil han kan lage instances av.

**Comment by skaugvoll** [comment]
@ingrskar , sender du meg ditt aws brukernavn, så kan jeg se om jeg får sendt/delt AMI med deg, og at du får satt opp _enkelt_ serveren og siste versjon ?

**Comment by skaugvoll** [comment]
Har funnet ut hvordan det skal gjores, men har ett problem, men jobber med det.
