### ISSUE TITLE
As a System maintainer
I want easily install the system as a VPS, So that as little technical detail and knowledge about the system is needed

### ISSUE THREAD

**Issue by MartinStigen** [ung-it/UngIT#8]
Priority: 100

**Comment by skaugvoll** [comment]
Denne trenge vell å renames til "standard VPS (virtual private server)", siden vi gikk bort fra web hotel

**Comment by skaugvoll** [comment]
Hva krever denne storien for å bli flyttet til Done? Hva er kravene, må jeg skrive en installasjons guide liksom?

**Comment by skaugvoll** [comment]
Lage en installasjonsguide, lage et image av ec2 instansen, skrive et scritp som starter og kjøre hvergang ec2 instansen starter opp, scriptet kjører Django applikasjonen

**Comment by skaugvoll** [comment]
AMI -> deles med Babak sin bruker

**Comment by skaugvoll** [comment]
samme som #53
